### ISSUE TITLE
1.8 hills?

### ISSUE THREAD

**Issue by jdtzmn** [AoHRuthless/King-of-the-Hill#12]
Does this plugin work in 1.8? You said on 'http://dev.bukkit.org/bukkit-plugins/king-of-the-hill/' that you were going to port this plugin with sponge api. I'm getting no errors saying that the arena isn't working, and players can join and battle, but the hill isn't working for some reason.

**Comment by jdtzmn** [comment]
Just tried resetting the config file. still doesn't work

**Comment by AoHRuthless** [comment]
I apologize, but this plugin has not been tested in 1.8 ... I lost all motivation to continue coding and I haven't begun to port the plugin to sponge yet. It will take a significant amount of time and I apologize for the inconvenience this causes you.
