### ISSUE TITLE
Unable to start koth

### ISSUE THREAD

**Issue by KnowItAllKing** [AoHRuthless/King-of-the-Hill#13]
What is the command to start it? When I attempt to /koth forcestart koth it doesn't show any error message or anything at all. I'm using the 1.8 version

**Comment by AoHRuthless** [comment]
Hi @KnowItAllKing,

What are the steps to reproduce this problem? Which version of KotH are you running? What are the settings for your arena? The command you are using should be correct.

Sorry for taking so long to respond, I haven't been working on this project recently.
